### ISSUE TITLE
Is 1.18 support in developement?

### ISSUE THREAD

**Issue by cmod31** [jediminer543/JMT-MCMT#102]
how far is the developement for 1.18 support?

**Comment by jediminer543** [comment]
I had been hoping for movement in forge because: https://github.com/McModLauncher/modlauncher/issues/89 is preventing a 1.17+ version from releasing without doing dodgy things; though forge clearly hasn't moved on it yet so I'll look into working on my own way around it

**Comment by cmod31** [comment]
So no fabric releases anymore? I found other performance fixes for my fabric server tho

**Comment by cmod31** [comment]
Forge has loading times that take years and bad performance so i'll use only fabric in the future

**Comment by imdioblack** [comment]
> I had been hoping for movement in forge because: [McModLauncher/modlauncher#89](https://github.com/McModLauncher/modlauncher/issues/89) is preventing a 1.17+ version from releasing without doing dodgy things; though forge clearly hasn't moved on it yet so I'll look into working on my own way around it

Spigot, maybe?

**Comment by jediminer543** [comment]
I'm using forge as it is the most expressive of the APIs. The forge api that let's me adjust dependencies is broken, yes, but it does exist. To do this in fabric previously needed grossfabrichacks which doesn't work (AFIK) post java9.

Bukkit and derivative APIs don't support bytecode transforms at all so would need an entire launchwrapper to allow for that

Also I'm working on forge 1.18 directly now because I have a hack for the issue in forge I think

**Comment by imdioblack** [comment]
@jediminer543 every time I read comments about what a mess Minecraft development is my respect for your work rises dramatically.

**Comment by jediminer543** [comment]
Am currently trying to tidy up so I can do stuff; and I am pleased to be able to close this issue with the [1.18-master branch](https://github.com/jediminer543/JMT-MCMT/tree/1.18-master)

**Comment by Zilacon** [comment]
Could you consider making a 1.12.2 version? There's hundreds of servers that would benefit from that.
