### ISSUE TITLE
1.18.1 Alpha causes OptiFine_1.18.1_HD_U_H5 Crash

### ISSUE THREAD

**Issue by ozma6464** [jediminer543/JMT-MCMT#110]
When adding the Alpha for 1.18.1 to my server it causes OptiFine_1.18.1_HD_U_H5 to crash immediately
[2022-03-25-2.log](https://github.com/jediminer543/JMT-MCMT/files/8350197/2022-03-25-2.log)

**Comment by ozma6464** [comment]
further testing shows that this mod is causing OptiFine_1.18.1_HD_U_H5 to crash on Client side as well. Minecraft client will not even load the Mojang Screen before crashing.

**Comment by ozma6464** [comment]
Removing OptiFine_1.18.1_HD_U_H5 resolves the issue and Minecraft loads with no problems on the Client

**Comment by jediminer543** [comment]
Compat with optifine is nigh impossible due to the fact that it is closed source and should only be touching client side stuff

If you want to use optifine my recommendation is to have a dedicated server with MCMT installed; and then install optifine on the client and not MCMT (MCMT is server side only anyway)
