### ISSUE TITLE
1.16.1 build 31 not start on dedicated server 

### ISSUE THREAD

**Issue by ptk2003** [jediminer543/JMT-MCMT#3]
[17:23:39] [main/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod ?ejmt_mcmt?r requires ?6minecraft?r ?o1.15.2?r
?7Currently, ?6minecraft?r?7 is ?o1.16.1

jar file 1.16.1, mc 1.16.1

jmt_mcmt-1.16.1-0.13.31
forge 108
[debug.log](https://github.com/jediminer543/JMT-MCMT/files/5097118/debug.log)

**Comment by jediminer543** [comment]
1 sec; I'll push a fix for that
That's a side effect of me mis-editing the mods.toml for that build

**Comment by jediminer543** [comment]
The underlying cause was fixed by using build.gradle to generate mods.toml files with the version data automagically [like this](https://github.com/jediminer543/JMT-MCMT/blob/5f9eb9d10343e7c371ed6b2b63e515e2eb16f81e/build.gradle#L163). Hence this issue is closed by 73806eee7ada66fe44c3f83d75a82a77d8de18ba

The new versions should never have that issue again as a result. I don't see the issue in testing, but please re-open this if it persists
