### ISSUE TITLE
Incompatibility with Clumps

### ISSUE THREAD

**Issue by BugmanBugman** [jediminer543/JMT-MCMT#38]
https://hatebin.com/bpbtzawgej

**Comment by KubiRem** [comment]
Can you be more specific please.
 For example in what time it happened (are you clicked something or what).
 With what mods this happened???
debug.log should be useful too.
In what version?
etc.

**Comment by BugmanBugman** [comment]
1.16.4
It just happened with MCMT and Clumps
Also I  don’t see the point of a debug log since it was just filled with the same error as the one I posted

**Comment by jediminer543** [comment]
This is an issue with clumps not being concurrent capible; I can look into adding a better solution but for now the best solution would be to disable world multithreading 

Run `/mcmt config world` and that should fix it

**Comment by jaredlll08** [comment]
I've gotten a few reports about this.

I have absolutely no interest in changing how clumps works, changing it would on my side would be like nerfing my own code, no thanks.

Also me fixing it on my side isn't going to solve other mods doing the same thing I am (which isn't even that weird, it's a simple iterator!).

Just a heads up, since I really don't like sifting through crash reports (where if you don't know to look for this mod, you aren't going to find the mod), I am going to be marking this mod as incompatible on CurseForge.

**Comment by jediminer543** [comment]
I've fixed this now, you can restore compatibility by setting `disableWorldPostTick = true` in the config file, which re-serialises the onWorldPostTick event

@jaredlll08 should I add a note of "how to change the config to make it compatible" and then you just leave the incompat flag set? IDK exactly how this works. Also sorry about this having been a pain, and I think I've properly hooked into the crash reports as of the latest release. (And sorry for the delayed response Uni + Mental health has been delaying this project)

**Comment by jaredlll08** [comment]
> And sorry for the delayed response Uni + Mental health has been delaying this project

You should never apologise for prioritising uni / health over mods.

I do think you should make a note about the config stuff though, since I'm sure Clumps can't be the only mod that this would affect.

As for the incompatability flag, I'll remove it for the time being (https://github.com/jaredlll08/Clumps/commit/1b2ea8c2abf459e4e9334fa032ee6b7b0ce6a37d), if I start getting reports about it I will unfortunately have to add it back, so lets see how it goes.

**Comment by jediminer543** [comment]
No problem; I'll look into an auto toggle for the onWorldPostTick hook (i.e. if exception occurs serialise) since it is likely there would be other compatibility things that may be less easy to track down.

And sorry again for causing you undue headache with bug reports, that was what I'd been trying to avoid
