### ISSUE TITLE
Some new problems

### ISSUE THREAD

**Issue by KubiRem** [jediminer543/JMT-MCMT#9]
Hello again after the new update i saw some corruption and lots of console spam from this mod that makes server not responding even after stop command.
Here is the logs for console spam thing.

[latest.log](https://github.com/jediminer543/JMT-MCMT/files/5161180/latest.log)
[debug.log](https://github.com/jediminer543/JMT-MCMT/files/5161181/debug.log)

BTW I am changed some plans I am in process of making  test in text form and I will publish it to You when I will be ready.
Best Regards
KubiRemPL

**Comment by jediminer543** [comment]
Ah

So the last update replaced one of the fastutil collections; It looks like having made that not error has caused others to error instead.

The first one will be quick to fix as I think I already have one, the latter will take more time; but it'll be fixed soon

Fix info for future me:

MCVER: 1.15

Repair targets:
- net.minecraft.world.chunk.storage.RegionSectionCache.func_219119_a (Long2ObjectOpenHashMap; I have one of these AFIK)
-  net.minecraft.world.lighting.LevelBasedGraph.func_215470_a (Long2ByteOpenHashMap; this needs making)

**Comment by jediminer543** [comment]
This should be fixed now as per the referenced issue (I finally did the thing properly WOO)

So I'm closing this now

Also sorry for the delay it took me an age to figure out what the feck was happening as I thought the issue was in the collections I was changing to but it was in the fecking Mojang code itself (Also IRL happened but that's less excusable)
